services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: picksleagues
      POSTGRES_PASSWORD: picksleagues
      POSTGRES_DB: picksleagues_dev
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
